name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:
  
permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Github actions have Node and Yarn already set-up by default
    # It is not clear which versions these are, 
    # so it might be a good idea to specify them via an action like actions/setup-node@v4
    - uses: actions/checkout@v4
    - name: Install
      run: yarn
    - name: Unit tests
      run: yarn test
    - name: Build
      run: yarn build
    - name: Integration tests
      run: yarn test:e2e
    - name: JUnit Report Action
      uses: mikepenz/action-junit-report@v5.6.2
 #     uses: EnricoMi/publish-unit-test-result-action@v2.20.0
      with:
        report_paths: "**/reports/**/*.xml"
        fail_on_failure: false

  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: version
        run: echo "version=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
      - name: Tag commit
        run: |
          git tag "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"
